# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=260, populate_from='name', verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Channels',
                'verbose_name': 'Channel',
            },
        ),
    ]
