# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(related_name='subcategories', to='category.Category', verbose_name='Parent category'),
        ),
    ]
