# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:11
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20160629_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=260, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
