# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20160629_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parents',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.Category', verbose_name='Parent category'),
        ),
    ]
